version: '3'
services:
  postgres:
    image: postgres:10
    container_name: postgres-bookstore
    ports:
      - "5432:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=bookstore
      - POSTGRES_USER=maradona
      - POSTGRES_PASSWORD=maradona
      - POSTGRES_PORT=5432
    volumes:
      - $PWD/volumes/postgres_data:/var/lib/postgresql/data
  wildfly:
    build: .
    image: booksfly
    container_name: wildfly-bookstore
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "9990:9990"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-bookstore
    ports:
      - "8081:80"
    links:
      - "postgres"
    environment:
      - PGADMIN_DEFAULT_EMAIL=maradona.morais@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=maradona
